exclude: ^tests/data/
repos:
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ["--ignore=E501,E126,W504,E741,E262,W503,E502,E402,E731,F841,E722,F405,F401"]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.961
  #   hooks:
  #     - id: mypy
  #       exclude: |-
  #         (?x)(
  #             ^test
  #             | ^docs
  #             | ^configs
  #         )
